# Generated by Django 5.0.3 on 2024-05-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('berapa_hari', models.CharField(max_length=10)),
                ('harga', models.CharField(max_length=10)),
            ],
        ),
    ]
