# Generated by Django 5.0.3 on 2024-05-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAMA', models.CharField(max_length=30)),
                ('TANGGAL_SEWA', models.DateField()),
                ('MOBIL', models.CharField(max_length=30)),
                ('BERAPA_HARI', models.CharField(max_length=30)),
            ],
        ),
    ]
